name: dartseid_example
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/exaby73/dartseid/tree/main/example
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  dartseid:
    path: ..
  json_annotation: ^4.8.1
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  lint: ^2.1.2
  test: ^1.21.0
