name: dartseid_example
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/exaby73/dartseid/tree/main/example

environment:
  sdk: ^3.0.5

dependencies:
  dartseid:
    path: ..
  path: ^1.8.0

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
