name: arcade
repository: https://github.com/dartarcade/arcade

packages:
  - packages/*

scripts:
  analyze:
    run: dart analyze
    
  format:
    exec: dart format lib

  test:
    exec: dart test
    packageFilters: 
      scope: '*'

  testArcadeOrm:
    exec: dart test --reporter=expanded --chain-stack-traces
    packageFilters: 
      scope: arcade_orm
