name: _

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - packages/arcade
  - packages/arcade/example
  - packages/arcade_cache
  - packages/arcade_cache_redis
  - packages/arcade_cli
  - packages/arcade_config
  - packages/arcade_logger
  - packages/arcade_swagger
  - packages/arcade_test
  - packages/arcade_views
  - samples/todo_api

dependencies:
  luthor:
    version: ^0.9.0
  prompts:
    version: ^2.0.0
  yaml_edit:
    version: ^2.2.2
