name: dartseid
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/exaby73/dartseid

environment:
  sdk: ^3.0.5

dependencies:
  collection: ^1.17.2
  hotreloader: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
