name: _

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - packages/arcade
  - packages/arcade_cache
  - packages/arcade_cache_redis
  - packages/arcade_cli
  - packages/arcade_config
  - packages/arcade_logger
  - packages/arcade_swagger
  - packages/arcade_test
  - packages/arcade_views
  - samples/todo_api

dependencies:
  args: ^2.7.0
  luthor:
    version: ^0.9.0
  prompts: ^2.0.0
  pubspec_parse: ^1.5.0
  yaml: ^3.1.3
  yaml_edit: ^2.2.2
