name: dartseid_cache
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/dartseid/dartseid/tree/main/packages/dartseid_cache

environment:
  sdk: ^3.0.5

# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
