name: dartseid_orm_sqlite_adapter
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  dartseid_orm: ^0.0.1

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
