name: arcade_cli
description: CLI for Arcade
version: 0.0.4
repository: https://github.com/dartarcade/arcade/tree/main/packages/arcade_cli

environment:
  sdk: ^3.0.6

dependencies:
  args: ^2.5.0
  path: ^1.9.0
  stream_transform: ^2.1.0
  watcher: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.7

executables:
  arcade: arcade_cli
