name: arcade_cli
description: CLI for Arcade
version: 0.5.0
repository: https://github.com/dartarcade/arcade/tree/main/packages/arcade_cli
issue_tracker: https://github.com/dartarcade/arcade/issues
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  arcade: ^0.5.0
  args: ^2.7.0
  path: ^1.9.1
  stream_transform: ^2.1.1
  watcher: ^1.1.2
  yaml: ^3.1.3

dev_dependencies:
  lint: ^2.8.0
  test: ^1.26.2

executables:
  arcade: arcade_cli
