name: arcade_cli
description: CLI for Arcade
version: 0.0.5
repository: https://github.com/dartarcade/arcade/tree/main/packages/arcade_cli
issue_tracker: https://github.com/dartarcade/arcade/issues
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  arcade: ^0.3.0
  args: ^2.6.0
  path: ^1.9.1
  stream_transform: ^2.1.0
  watcher: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.12

executables:
  arcade: arcade_cli
