name: arcade_cli
description: CLI for Dartseid
version: 0.0.3+1
repository: https://github.com/dartarcade/arcade/tree/main/packages/arcade_cli

environment:
  sdk: ^3.0.6

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  stream_transform: ^2.1.0
  watcher: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0

executables:
  arcade: arcade_cli
