# https://taskfile.dev

version: '3'

tasks:
  default:
    run: always
    cmds:
      - clear
      - dart run bin/dartseid_cli.dart {{.CLI_ARGS}}
    sources:
      - bin/**/*.*
      - lib/**/*.*
