name: dartseid_views
description: Add views to your Dartseid application
version: 0.0.5
repository: https://github.com/exaby73/dartseid/tree/master/packages/dartseid_views

environment:
  sdk: ^3.0.5

dependencies:
  dartseid_config: ^0.0.2
  mustache_template: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
