name: dartseid_logger
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/dartseid/dartsied/tree/main/packages/dartseid_logger

environment:
  sdk: ^3.0.5

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
