name: dartseid_logger
description: A logger for Dartseid
version: 1.0.0
repository: https://github.com/dartseid/dartsied/tree/main/packages/dartseid_logger

environment:
  sdk: ^3.0.5

dependencies:
  ansi_styles: ^0.3.2+1
  dartseid: ^0.0.7

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
