name: dartseid_config
description: Configuration for your Dartseid app
version: 0.0.1
repository: https://github.com/dartseid/dartseid/tree/main/packages/dartsied_config

environment:
  sdk: ^3.0.5

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
