include: package:lint/analysis_options.yaml

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    implicit_call_tearoffs: ignore
  exclude:
    - "**/*.config.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
