services:
  db:
    image: postgres:17-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  admin:
    image: dpage/pgadmin4:latest
    restart: always
    volumes:
      - pgadmindata:/var/lib/pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: db@todo.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db

volumes:
  pgdata:
  pgadmindata: