name: dartseid
description: A no magic web framework for Dart.
version: 0.1.0+1
repository: https://github.com/exaby73/dartseid

environment:
  sdk: ^3.0.5

dependencies:
  collection: ^1.17.2
  dartseid_config: ^0.0.2
  dartseid_logger: ^0.0.2
  mime: ^1.0.4
  path: ^1.8.3
  string_scanner: ^1.2.0
  uuid: ^3.0.7

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.3
