name: dartseid
description: A no magic web framework for Dart.
version: 0.0.7
repository: https://github.com/exaby73/dartseid

environment:
  sdk: ^3.0.5

dependencies:
  ansi_styles: ^0.3.2+1
  collection: ^1.17.2
  dartseid_logger: ^0.0.1
  hotreloader: ^3.0.6
  mime: ^1.0.4
  path: ^1.8.3
  string_scanner: ^1.2.0
  vm_service: ^11.7.2

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.3
