name: dartseid
description: A no magic web framework for Dart.
version: 0.0.2
repository: https://github.com/exaby73/dartseid

environment:
  sdk: ^3.0.5

dependencies:
  ansi_styles: ^0.3.2+1
  collection: ^1.17.2
  hotreloader: ^3.0.6
  vm_service: ^11.7.1

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
