name: Analyze Dart Packages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Install DPK
        run: dart pub global activate dpk
      - name: Run dpk get
        run: dpk get
      - name: Analyze
        run: dpk run analyze
      - name: Format
        run: dpk run format
