name: Test arcade_cache_redis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      
      - name: Install DPK
        run: dart pub global activate dpk
      
      - name: Start Redis with Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.yml
          services: redis
      
      - name: Run dpk get
        run: dpk get
        
      - name: Run tests
        run: dpk run test:redis